personData1:
  firstName: "Оксана"
  reportDate: "сегодня"

personData2:
  firstName: "Зинаида"
  reportDate: "сегодня"

answers1:
  what:
    "1": "НЕТ"
    "2": "НЕТ"
    "3": "ДА"
    "4": "НЕТ"
    "5": "НЕТ"
  why:
    "1": "НЕТ"
    "2": "НЕТ"
    "3": "НЕТ"
    "4": "НЕТ"
  properties:
    "1": "ДА"
    "2": "НЕТ"
    "3": "ДА"
  threat:
    "1": "НЕТ"
    "2": "ДА"
    "3": "НЕТ"
    "4": "НЕТ"
    "5": "НЕТ"
  incidentType: "Инцидент ИБ"

answers2:
  what:
    "1": "ДА"
    "2": "ДА"
    "3": "НЕТ"
    "4": "НЕТ"
    "5": "НЕТ"
  why:
    "1": "ДА"
    "2": "НЕТ"
    "3": "НЕТ"
    "4": "НЕТ"
  properties:
    "1": "НЕТ"
    "2": "НЕТ"
    "3": "ДА"
  threat:
    "1": "ДА"
    "2": "НЕТ"
    "3": "НЕТ"
    "4": "ДА"
    "5": "ДА"
  incidentType: "Инцидент ИБ"
