personData1:
  lastName: "Иванова"
  firstName: "Надежда"
  middleName: "Викторовна"
  position: "специалист"
  department: "Отдел инноваций"
  reportDate: "06.04.2026"

personData2:
  lastName: "Команец"
  firstName: "Ольга"
  middleName: "Андреевна"
  position: "Начальник отдела"
  department: "Отдел по работе с одаренными детьми"
  reportDate: "06.04.2026"

answers1:
  what:
    "1": "НЕТ"
    "2": "ДА"
    "3": "НЕТ"
    "4": "НЕТ"
    "5": "НЕТ"
  why:
    "1": "НЕТ"
    "2": "НЕТ"
    "3": "НЕТ"
    "4": "ДА"
  properties:
    "1": "НЕТ"
    "2": "НЕТ"
    "3": "НЕТ"
  threat:
    "1": "НЕТ"
    "2": "НЕТ"
    "3": "НЕТ"
    "4": "ДА"
    "5": "ДА"
  incidentType: "Инцидент ИБ"

answers2:
  what:
    "1": "НЕТ"
    "2": "НЕТ"
    "3": "НЕТ"
    "4": "ДА"
    "5": "НЕТ"
  why:
    "1": "НЕТ"
    "2": "ДА"
    "3": "НЕТ"
    "4": "НЕТ"
  properties:
    "1": "ДА"
    "2": "НЕТ"
    "3": "НЕТ"
  threat:
    "1": "НЕТ"
    "2": "НЕТ"
    "3": "НЕТ"
    "4": "НЕТ"
    "5": "ДА"
  incidentType: "Инцидент ИБ"
