personData1:
  lastName: "Кузнецова"
  firstName: "Оксана"
  middleName: "Николаевна"
  position: "Секретарь канцелярии"
  department: "Канцелярия"
  reportDate: "06.04.2026"

personData2:
  lastName: "Морева"
  firstName: "Зинаида"
  middleName: "Олеговна"
  position: "Главный бухгалтер"
  department: "Бухгалтерия"
  reportDate: "06.04.2026"

answers1:
  what:
    "1": "ДА"
    "2": "НЕТ"
    "3": "НЕТ"
    "4": "НЕТ"
    "5": "НЕТ"
  why:
    "1": "НЕТ"
    "2": "НЕТ"
    "3": "НЕТ"
    "4": "НЕТ"
  properties:
    "1": "НЕТ"
    "2": "НЕТ"
    "3": "НЕТ"
  threat:
    "1": "ДА"
    "2": "НЕТ"
    "3": "НЕТ"
    "4": "НЕТ"
    "5": "НЕТ"
  incidentType: "Событие ИБ"

answers2:
  what:
    "1": "НЕТ"
    "2": "НЕТ"
    "3": "ДА"
    "4": "НЕТ"
    "5": "НЕТ"
  why:
    "1": "НЕТ"
    "2": "НЕТ"
    "3": "ДА"
    "4": "НЕТ"
  properties:
    "1": "ДА"
    "2": "ДА"
    "3": "НЕТ"
  threat:
    "1": "НЕТ"
    "2": "ДА"
    "3": "НЕТ"
    "4": "НЕТ"
    "5": "ДА"
  incidentType: "Инцидент ИБ"
