personData1:
  lastName: "Смирнова"
  firstName: "Ирина"
  middleName: "Петровна"
  position: "специалист"
  department: "Отдел методического обеспечения"
  reportDate: "06.04.2026"

personData2:
  lastName: "Воронцов"
  firstName: "Аркадий"
  middleName: "Сергеевич"
  position: "инспектор"
  department: "Отдела кадров"
  reportDate: "06.04.2026"

answers1:
  what:
    "1": "ДА"
    "2": "ДА"
    "3": "НЕТ"
    "4": "НЕТ"
    "5": "НЕТ"
  why:
    "1": "ДА"
    "2": "НЕТ"
    "3": "НЕТ"
    "4": "НЕТ"
  properties:
    "1": "НЕТ"
    "2": "НЕТ"
    "3": "ДА"
  threat:
    "1": "НЕТ"
    "2": "НЕТ"
    "3": "НЕТ"
    "4": "ДА"
    "5": "ДА"
  incidentType: "Инцидент ИБ"

answers2:
  what:
    "1": "НЕТ"
    "2": "НЕТ"
    "3": "НЕТ"
    "4": "НЕТ"
    "5": "ДА"
  why:
    "1": "НЕТ"
    "2": "НЕТ"
    "3": "НЕТ"
    "4": "НЕТ"
  properties:
    "1": "НЕТ"
    "2": "НЕТ"
    "3": "НЕТ"
  threat:
    "1": "ДА"
    "2": "НЕТ"
    "3": "НЕТ"
    "4": "НЕТ"
    "5": "НЕТ"
  incidentType: "Событие ИБ"
